import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const configEnvSchema = new Map();

function registerEnv(name, type, fallback) {
  const existing = configEnvSchema.get(name);
  if (existing && existing.type !== type) throw new Error(`Config env ${name} registered with conflicting types`);
  if (!existing) configEnvSchema.set(name, Object.freeze({ name, type, default: fallback }));
}

function stringFromEnv(name, fallback = '') {
  registerEnv(name, 'string', fallback);
  const raw = process.env[name];
  return raw == null || raw === '' ? fallback : raw;
}

function intFromEnv(name, fallback) {
  registerEnv(name, 'integer', fallback);
  const raw = process.env[name];
  if (raw == null || raw === '') return fallback;

  const value = Number.parseInt(raw, 10);
  if (!Number.isFinite(value)) throw new Error(`Invalid integer env ${name}: ${raw}`);
  return value;
}

function boolFromEnv(name, fallback) {
  registerEnv(name, 'boolean', fallback);
  const raw = process.env[name];
  if (raw == null || raw === '') return fallback;
  return /^(1|true|yes|on)$/i.test(raw);
}

function csvFromEnv(name, fallback) {
  registerEnv(name, 'csv', fallback);
  const raw = process.env[name];
  const source = raw == null || raw === '' ? fallback : raw;
  return String(source)
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

export const DEFAULT_DATA_DIR = path.join(os.homedir(), '.bridge-data');
const ENV_FILE = stringFromEnv('ENV_FILE', path.join(stringFromEnv('DATA_DIR', DEFAULT_DATA_DIR), '.env'));

function loadDotEnv(filePath = ENV_FILE) {
  const absolutePath = path.resolve(filePath);
  if (!fs.existsSync(absolutePath)) return;

  const content = fs.readFileSync(absolutePath, 'utf8');
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const index = line.indexOf('=');
    if (index === -1) continue;

    const key = line.slice(0, index).trim();
    if (!key || process.env[key] != null) continue;

    let value = line.slice(index + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    process.env[key] = value;
  }
}

function token() {
  return crypto.randomBytes(48).toString('base64url');
}

function envLine(key, value) {
  return `${key}=${String(value).replace(/\n/g, '')}`;
}

function ensureDotEnv(filePath = ENV_FILE) {
  const absolutePath = path.resolve(filePath);
  const generated = [];
  const defaults = {
    HOST: '127.0.0.1',
    PORT: '8080',
    API_TOKEN: token(),
    BRIDGE_TOKEN: token(),
    DATA_DIR: process.env.DATA_DIR || DEFAULT_DATA_DIR,
  };

  if (process.env.PUBLIC_BASE_URL == null) {
    defaults.PUBLIC_BASE_URL = `http://${process.env.HOST || defaults.HOST}:${process.env.PORT || defaults.PORT}`;
  }

  let existing = '';
  try {
    existing = fs.existsSync(absolutePath) ? fs.readFileSync(absolutePath, 'utf8') : '';
  } catch {
    return { path: absolutePath, generated };
  }

  const existingKeys = new Set();
  for (const rawLine of existing.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const index = line.indexOf('=');
    if (index > 0) existingKeys.add(line.slice(0, index).trim());
  }

  const additions = [];
  for (const [key, value] of Object.entries(defaults)) {
    if (process.env[key] != null || existingKeys.has(key)) continue;
    additions.push(envLine(key, value));
    process.env[key] = value;
    generated.push(key);
  }

  if (!additions.length) return { path: absolutePath, generated };

  try {
    fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
    const prefix = existing && !existing.endsWith('\n') ? '\n' : '';
    const header = existing ? '\n# Generated by chatgpt-browser-bridge setup\n' : '# Generated by chatgpt-browser-bridge setup\n';
    fs.writeFileSync(absolutePath, `${existing}${prefix}${header}${additions.join('\n')}\n`, 'utf8');
  } catch {
    // Keep generated values in process.env even if the file cannot be written.
  }

  return { path: absolutePath, generated };
}

loadDotEnv();
export const setupInfo = ensureDotEnv();
loadDotEnv();

export const config = Object.freeze({
  generatedEnv: setupInfo.generated,
  envFile: setupInfo.path,
  host: stringFromEnv('HOST', '127.0.0.1'),
  port: intFromEnv('PORT', 8080),
  apiToken: stringFromEnv('API_TOKEN', ''),
  activeClientId: stringFromEnv('ACTIVE_CLIENT_ID', ''),
  autoOpenTab: boolFromEnv('AUTO_OPEN_TAB', false),
  autoOpenTabTimeoutMs: intFromEnv('AUTO_OPEN_TAB_TIMEOUT_MS', 30_000),
  autoOpenTabBootstrapWaitMs: intFromEnv('AUTO_OPEN_TAB_BOOTSTRAP_WAIT_MS', 2_500),
  payloadDebug: boolFromEnv('PAYLOAD_DEBUG', false),
  payloadDebugFile: path.resolve(stringFromEnv('PAYLOAD_DEBUG_FILE', path.join(stringFromEnv('DATA_DIR', DEFAULT_DATA_DIR), 'last_openclaw_payload.json'))),
  jsonBodyLimit: stringFromEnv('JSON_BODY_LIMIT', '50mb'),
  dataDir: path.resolve(stringFromEnv('DATA_DIR', DEFAULT_DATA_DIR)),
  answerTimeoutMs: intFromEnv('ANSWER_TIMEOUT_MS', 120_000),
  requestMeaningfulProgressTimeoutMs: intFromEnv('REQUEST_MEANINGFUL_PROGRESS_TIMEOUT_MS', intFromEnv('ANSWER_TIMEOUT_MS', 120_000)),
  requestPostGenerationProgressTimeoutMs: intFromEnv('REQUEST_POST_GENERATION_PROGRESS_TIMEOUT_MS', 60_000),
  requestHardLivenessTimeoutMs: intFromEnv('REQUEST_HARD_LIVENESS_TIMEOUT_MS', Math.max(60_000, intFromEnv('CLIENT_STALE_MS', 30_000) + intFromEnv('HEARTBEAT_INTERVAL_MS', 10_000))),
  requestGenerationActivityGraceMs: intFromEnv('REQUEST_GENERATION_ACTIVITY_GRACE_MS', 30_000),
  forcedSnapshotAfterMs: intFromEnv('FORCED_SNAPSHOT_AFTER_MS', 90_000),
  forcedSnapshotCooldownMs: intFromEnv('FORCED_SNAPSHOT_COOLDOWN_MS', 60_000),
  forcedSnapshotTimeoutMs: intFromEnv('FORCED_SNAPSHOT_TIMEOUT_MS', 30_000),
  answerSettleMs: intFromEnv('ANSWER_SETTLE_MS', 1500),
  answerDoneSettleMs: intFromEnv('ANSWER_DONE_SETTLE_MS', 600),
  postStopTerminalSettleMs: intFromEnv('POST_STOP_TERMINAL_SETTLE_MS', 900),
  requiredArtifactSettleMs: intFromEnv('REQUIRED_ARTIFACT_SETTLE_MS', 30_000),
  promptDeliveryTimeoutMs: intFromEnv('PROMPT_DELIVERY_TIMEOUT_MS', 30_000),
  promptAcceptedTimeoutMs: intFromEnv('PROMPT_ACCEPTED_TIMEOUT_MS', 10_000),
  chatGptTransientErrorMaxRetries: intFromEnv('CHATGPT_TRANSIENT_ERROR_MAX_RETRIES', 3),
  chatGptTransientErrorRetryBaseMs: intFromEnv('CHATGPT_TRANSIENT_ERROR_RETRY_BASE_MS', 1_000),
  chatGptTransientErrorRetryMaxMs: intFromEnv('CHATGPT_TRANSIENT_ERROR_RETRY_MAX_MS', 8_000),
  heartbeatIntervalMs: intFromEnv('HEARTBEAT_INTERVAL_MS', 10_000),
  clientStaleMs: intFromEnv('CLIENT_STALE_MS', 30_000),
  debugEventsLimit: intFromEnv('DEBUG_EVENTS_LIMIT', 250),
  bridgeToken: stringFromEnv('BRIDGE_TOKEN', ''),
  publicBaseUrl: stringFromEnv('PUBLIC_BASE_URL', `http://${stringFromEnv('HOST', '127.0.0.1')}:${intFromEnv('PORT', 8080)}`),
  attachmentTransport: stringFromEnv('ATTACHMENT_TRANSPORT', 'url'),
  artifactChunkTimeoutMs: intFromEnv('ARTIFACT_CHUNK_TIMEOUT_MS', 60_000),
  artifactResolveRetries: intFromEnv('ARTIFACT_RESOLVE_RETRIES', 5),
  artifactResolveRetryDelayMs: intFromEnv('ARTIFACT_RESOLVE_RETRY_DELAY_MS', 600),
  artifactRetentionCount: intFromEnv('ARTIFACT_RETENTION_COUNT', 10),
  artifactRetentionBytes: intFromEnv('ARTIFACT_RETENTION_BYTES', 250 * 1024 * 1024),
  zipMaxEntries: intFromEnv('ZIP_MAX_ENTRIES', 5000),
  zipMaxUncompressedSize: intFromEnv('ZIP_MAX_UNCOMPRESSED_SIZE', 500 * 1024 * 1024),
  projectMaxFiles: intFromEnv('PROJECT_MAX_FILES', 2000),
  projectMaxZipBytes: intFromEnv('PROJECT_MAX_ZIP_BYTES', 50 * 1024 * 1024),
  projectMaxSingleFileBytes: intFromEnv('PROJECT_MAX_SINGLE_FILE_BYTES', 1024 * 1024),
  projectContextMaxSymbols: intFromEnv('PROJECT_CONTEXT_MAX_SYMBOLS', 2000),
  projectTreeLimit: intFromEnv('PROJECT_TREE_LIMIT', 500),
  allowedOrigins: csvFromEnv('ALLOWED_ORIGINS', 'https://chatgpt.com,https://chat.openai.com,null'),
});

export const CONFIG_ENV_SCHEMA = Object.freeze(Object.fromEntries(configEnvSchema));
